# baseURL = 'https://serabikocorbuyuni.my.id/'
languageCode = 'en-us'
title = 'Serabi Kocor Bu Yuni'
icon = "/favicon.ico"
DisqusShortname="serabikocorbuyuni"

enableEmoji = true
enableGitInfo = true
enableRobotsTXT = true
canonifyURLs = true

[outputs]
    home = ["HTML", "RSS", "JSON"]
    pages = ["HTML", "RSS", "JSON"]
    blog = ["HTML", "RSS", "JSON"]
    page = ["HTML", "RSS", "JSON"]

[taxonomies]
  tags = "tags"

[permalinks]
  blog = "/blog/:slug/"
  pages = "/pages/:slug/"

[frontmatter]
date = ["date", "publishDate", "lastmod"]
lastmod = [":git", "lastmod", "date", "publishDate"]
publishDate = ["publishDate", "date"]
expiryDate = ["expiryDate"]

copyright = 'This work is licensed under a Creative Commons Attribution-ShareAlike 4.0 International License.'

[sitemap]
  changefreq = 'monthly'
  filename = 'sitemap.xml'
  priority = 0.5

[params]
profile_serabi = "/img/serabi"
profile_muryp = "/img/muryp"
description_serabi = "Hai, apa kalian ingin mencoba kuliner serabi khas ngampin ambarawa? Mampir ke tempat kami ya, bisa dicoba kualitas serabi kami."
description_writer = "Front End Developer"
name_toko = "Serabi Kocor Bu Yuni"
name_writer = "Muryp"
