[[nav]]
name = "Home"
identifier = "ihome"
url = "#"
weight = 1
[[nav]]
name = "About"
identifier = "iabout"
url = "#about"
weight = 2
[[nav]]
name = "Contact"
identifier = "tlp"
url = "#contact"
weight = 3
[[nav]]
name = "Menu"
identifier = "imenu"
url = "#menu"
weight = 4
[[nav]]
name = "Blog"
identifier = "ialbum"
url = "/blog"
weight = 5

[[post]]
name = "Home"
identifier = "ihome"
url = "/"
weight = 1
[[post]]
name = "About"
identifier = "iabout"
url = "#about"
weight = 2
[[post]]
name = "Contact"
identifier = "tlp"
url = "#contact"
weight = 3
[[post]]
name = "Blog"
identifier = "imenu"
url = "#Blog"
weight = 4
[[post]]
name = "Gallery"
identifier = "ialbum"
url = "#Gallery"
weight = 5

[[sosmed]]
identifier = "fb"
name = "@serabikocorbuyuni"
url = "facebook.com/serabikocorbuyuni"
weight = 1
[[sosmed]]
identifier = "ig"
name = "@serabikocorbuyuni"
url = "instagram.com/serabikocorbuyuni"
weight = 2
[[sosmed]]
identifier = "tw"
name = "@serabikocorbuyuni"
url = "twitter.com/serabibuyuni"
weight = 3
