[[nav]]
identifier = "Home"
name = "ihome"
url = "#"
weight = 1
[[nav]]
identifier = "About"
name = "iabout"
url = "#about"
weight = 2
[[nav]]
identifier = "Contact"
name = "tlp"
url = "#contact"
weight = 3
[[nav]]
identifier = "Menu"
name = "imenu"
url = "#menu"
weight = 4
[[nav]]
identifier = "Blog"
name = "ialbum"
url = "/blog"
weight = 5

[[post]]
identifier = "Home"
name = "ihome"
url = "/"
weight = 1
[[post]]
identifier = "About"
name = "iabout"
url = "/about"
weight = 2
[[post]]
identifier = "Contact"
name = "tlp"
url = "/contact"
weight = 3
[[post]]
identifier = "Blog"
name = "imenu"
url = "/Blog"
weight = 4
[[post]]
identifier = "Menu Kuliner"
name = "imenu"
url = "/#Menu"
weight = 5

# sosmed serabi -----------------------------
[[sosmed]]
identifier = "fb"
name = "@serabikocorbuyuni"
url = "facebook.com/serabikocorbuyuni"
weight = 1
[[sosmed]]
identifier = "ig"
name = "@serabikocorbuyuni"
url = "instagram.com/serabikocorbuyuni"
weight = 2
[[sosmed]]
identifier = "tw"
name = "@serabikocorbuyuni"
url = "twitter.com/serabibuyuni"
weight = 3

# contact serabi -----------------------------
[[contact]]
identifier = "tlp"
name = "+628-1325-269068"
url = "https://wa.me/message/M3B4KVEFVVTYJ1"
weight = 1
[[contact]]
identifier = "gmail"
name = "bicor@gmail.com"
url = "mailto:bicor@gmail.com"
weight = 2

# sosmed muryp -----------------------------
[[sosmed2]]
identifier = "fb"
name = "@alifprihantoro"
url = "facebook.com/alifprihantoro"
weight = 1
[[sosmed2]]
identifier = "ig"
name = "@alifprihantoro"
url = "instagram.com/alifprihantoro"
weight = 2
[[sosmed2]]
identifier = "tw"
name = "@alifprihantoro"
url = "twitter.com/alifprihantoro"
weight = 3
