[[nav]]
identifier = "About"
name = "iabout"
url = "#about"
[[nav]]
identifier = "Contact"
name = "tlp"
url = "#contact"
[[nav]]
identifier = "Blog"
name = "imenu"
url = "#Blog"
[[nav]]
identifier = "Gallery"
name = "ialbum"
url = "#Gallery"
