[[nav]]
identifier = "About"
name = "iabout"
url = "#about"
[[nav]]
identifier = "Contact"
name = "tlp"
url = "#contact"
[[nav]]
identifier = "Menu"
name = "imenu"
url = "#menu"
[[nav]]
identifier = "Album"
name = "ialbum"
url = "#album"
