[[sosmed]]
identifier = "fb"
name = "@serabikocorbuyuni"
url = "facebook.com/serabikocorbuyuni"
weight = 1
[[sosmed]]
identifier = "ig"
name = "@serabikocorbuyuni"
url = "instagram.com/serabikocorbuyuni"
weight = 2
[[sosmed]]
identifier = "tw"
name = "@serabikocorbuyuni"
url = "twitter.com/serabibuyuni"
weight = 3
